### ISSUE TITLE
However, there is only one process accept request, others will aways idel

### ISSUE THREAD

**Issue by logig** [deemru/php-cgi-spawner#10]
I write a simple code to test this, the sleep call block other requests anyway.

```<?php
if(isset($_REQUEST['sleep'])) sleep($_REQUEST['sleep']);
echo time();
```

**Comment by deemru** [comment]
Please, provide more info to reproduce, a start command at least.

**Comment by logig** [comment]
Win10 + Nginx 
```
export PHP_HELP_MAX_REQUESTS=1000
./php-cgi-spawner.exe php-cgi.exe 9000 1+6 &
```

**Comment by logig** [comment]
My nginx config
```
location ~ [^/]\.php(/|$) {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
```

**Comment by logig** [comment]
The same with run php-cgi.exe manualy, only one process will accept requests. Something wrong with my PC?
```
./php-cgi.exe -b 127.0.0.1:9000 &
./php-cgi.exe -b 127.0.0.1:9000 &
./php-cgi.exe -b 127.0.0.1:9000 &
```

**Comment by logig** [comment]
I think this is the problem of operation system. 
Node.js has this pit with Windows too.

**Comment by deemru** [comment]
This is strange. Did you tried `php-cgi-spawner.exe php-cgi.exe 9000 4` not `1+6`?

**Comment by logig** [comment]
I tried, and the result is the same. All requests must be lined up.

**Comment by deemru** [comment]
Cannot reproduce.

**Comment by logig** [comment]
Why do you think php-fpm doesn't publish a Windows version?

**Comment by deemru** [comment]
php-fpm based on unix only features, there is no such API in windows os.

**Comment by logig** [comment]
So do you think php-cgi-spawner can make up for this?

**Comment by deemru** [comment]
If possible, it would be done long ago.

However, Windows now have [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), try it if you need php-fpm.
