### ISSUE TITLE
Run as service

### ISSUE THREAD

**Issue by tarreislam** [deemru/php-cgi-spawner#5]
Hey, I have been looking for something like this for a long time, it is really great, but to use this as an WINDOWS service would be even better, do you have any plans on doing this or is it even possible to use a service wrapper with this?

**Comment by deemru** [comment]
Thanks, but:
- Developers of PHP 7.1 finally applied the same process spawning technic to php-cgi for Windows to support concurrent processing of multiple requests natively (see `CreateProcess` at [cgi_main.c](https://github.com/php/php-src/blob/PHP-7.1/sapi/cgi/cgi_main.c))
- There is no plan to develop this app any further or info about service wrappers

**Comment by tarreislam** [comment]
Thats great, but 7.1 is not in release yet. Anyway i found out it is possible to wrap it and run your program as a Service, it could be useful to people stuck < php 7

`Nssm install "Php-cgi-spawner" "php-cgi-spawner.exe" "\"core/php/php-cgi.exe -c core/php/php.ini\" 9000 5"`

https://nssm.cc/ ( the Non-Sucking Service Manager)

**Comment by deemru** [comment]
Thank you, solved
