### ISSUE TITLE
Detected malware

### ISSUE THREAD

**Issue by Koumes** [deemru/php-cgi-spawner#6]
Virustotal.com reports malware in the php-cgi-spawner.exe and Windows Defender removing it.

[Scan Report](https://www.virustotal.com/cs/file/f7360e3d57748c7bec66ec8e53a717da8c66d4aca25a9ee313a608c14c731ccc/analysis/1472806029/): 

Antivirus   Result  Update
Baidu   Win32.Trojan.WisdomEyes.151026.9950.9999    20160902
CrowdStrike Falcon (ML) malicious_confidence_67% (D)    20160725
Cyren   W32/Threat-HLLSI-based!Maximus  20160902
F-Prot  W32/Threat-HLLSI-based!Maximus  20160902

**Comment by deemru** [comment]
It seems the php-cgi-spawner code has some sort of functionality which is common to a malware, namely it spawns other processes.

Some antiviruses detect it as a threat, it is their right.

As you can see, every release have a link to a build log on AppVeyor, for example the last one: https://ci.appveyor.com/project/deemru/php-cgi-spawner/build/1.0.20

Finally, you can build the application by yourself if you do not trust AppVeyor.
